from __future__ import annotations

from pathlib import Path


def test_phase2_evidence_report_records_required_claim_decisions():
    report = Path("results/phase2/PHASE2_EVIDENCE_REPORT.md")
    assert report.exists()
    text = report.read_text(encoding="utf-8")
    required = [
        "observability gap",
        "cheap probes close",
        "VOI probing",
        "active route-state calibration",
        "ICML/ICLR-style paper",
        "table_observability_strong_encoders.csv",
        "table_probe_signal_analysis.csv",
        "table_proberoute_policy.csv",
        "table_probe_cost_sensitivity.csv",
        "table_probe_cost_sensitivity_summary.csv",
        "fig_probe_cost_sensitivity.pdf",
        "table_active_new_model_calibration.csv",
        "table_active_calibration_replicates.csv",
        "table_active_calibration_replicate_summary.csv",
        "table_active_calibration_active_vs_uniform_deltas.csv",
        "table_active_calibration_active_vs_random_deltas.csv",
        "table_active_calibration_active_vs_dataset_deltas.csv",
        "table_active_calibration_active_vs_embedding_deltas.csv",
        "table_active_calibration_sensitivity.csv",
        "table_active_calibration_sensitivity_summary.csv",
        "table_active_calibration_sensitivity_deltas.csv",
        "exact_manifest_probe_features.parquet",
        "exact_manifest_probes_eval/table_probe_signal_analysis.csv",
        "local_qwen3_4b_transformers_smoke/local_model_outcomes.parquet",
        "local_qwen3_4b_transformers_smoke/probe_features.parquet",
        "local_exact_manifest_qwen3_4b_transformers/local_model_outcomes.parquet",
        "exact_manifest_probes_qwen3_4b_transformers/exact_manifest_probe_features.parquet",
        "exact_manifest_probes_qwen3_4b_transformers_eval/table_probe_signal_analysis.csv",
        "all200_exact_task_manifest/local_exact_task_manifest.csv",
        "local_all200_qwen3_4b_transformers/local_model_outcomes.parquet",
        "exact_manifest_probes_all200_qwen3_4b_transformers/exact_manifest_probe_features.parquet",
        "exact_manifest_probes_all200_qwen3_4b_transformers_eval/table_probe_signal_analysis.csv",
        "true_probe_policy_inputs_all200_qwen3_4b_transformers/true_probe_before_beliefs.csv",
        "true_probe_policy_inputs_all200_qwen3_4b_transformers/true_probe_after_beliefs.csv",
        "true_probe_policy_all200_qwen3_4b_transformers/table_proberoute_policy.csv",
        "true_probe_policy_cost_sensitivity_all200_qwen3_4b_transformers/table_probe_cost_sensitivity_summary.csv",
        "true_probe_policy_cost_sensitivity_all200_qwen3_4b_transformers/fig_probe_cost_sensitivity.pdf",
        "true_probe_decision_value_all200_qwen3_4b_transformers/table_true_probe_decision_value.csv",
        "true_probe_decision_value_all200_qwen3_4b_transformers/table_true_probe_decision_value_by_query.csv",
        "local_server_readiness_vllm_qwen3_4b/table_local_server_readiness.csv",
        "local_vllm_qwen3_4b_exact_smoke_nothink/local_model_outcomes.parquet",
        "exact_manifest_probes_vllm_qwen3_4b_smoke/exact_manifest_probe_features.parquet",
        "exact_manifest_probes_vllm_qwen3_4b_smoke_eval/table_probe_signal_analysis.csv",
        "local_vllm_qwen3_4b_all200_nothink/local_model_outcomes.parquet",
        "exact_manifest_probes_vllm_qwen3_4b_all200/exact_manifest_probe_features.parquet",
        "exact_manifest_probes_vllm_qwen3_4b_all200_eval/table_probe_signal_analysis.csv",
        "true_probe_policy_inputs_vllm_qwen3_4b_all200/true_probe_before_beliefs.csv",
        "true_probe_policy_vllm_qwen3_4b_all200/table_proberoute_policy.csv",
        "true_probe_decision_value_vllm_qwen3_4b_all200/table_true_probe_decision_value.csv",
        "true_probe_policy_cost_sensitivity_vllm_qwen3_4b_all200/table_probe_cost_sensitivity_summary.csv",
        "vllm_probe_variant_comparison/table_vllm_probe_variant_summary.csv",
        "routecode_target_rate_policy_inputs_vllm_all200",
        "routecode_target_rate_policy_vllm_all200",
        "oracle_gap_gate_vllm_all200/table_oracle_gap_gate.csv",
        "benchmark_label_policy_exact_math_vllm_all200/table_policy_summary.csv",
        "benchmark_label_policy_exact_math_vllm_all200/table_policy_selections.csv",
        "table_phase2_completion_audit.csv",
        "phase2_completion_audit.md",
        "implementation_task | complete | 14",
        "queries=200;rows=400;local_models=2",
        "oracle_gap_core_policy_3pct",
        "best_current_policy_relative_gap=0.0263",
        "oracle_gap_true_probe_policy_3pct",
        "best_true_probe_policy_relative_gap=0.0789",
        "oracle_gap_target_rate_routecode_3pct",
        "target_k=32;target_rate_policy_slice_gap=0.0263",
        "oracle_gap_operational_fallback_3pct",
        "benchmark_label_relative_gap=0.0000",
        "Multi-Endpoint vLLM Scale Support",
        "phase2_local_eval.openai_endpoints",
        "configs/phase2_local_vllm_two_model_all200_nothink.yaml",
        "experiments/71_local_vllm_policy_pipeline.py",
        "Qwen/Qwen3-0.6B",
        "qwen3_0_6b_vllm",
        "VLLM_USE_V2_MODEL_RUNNER=0",
        "ninja",
        "RuntimeError: UVA is not available",
        "local_vllm_launch_attempt_memo.md",
        "local_server_readiness_phase2_local_vllm_two_model_all200_nothink/table_local_server_readiness.csv",
        "results/phase2/local_vllm_two_model_all200_nothink/local_model_outcomes.parquet",
        "The readiness table passed with two ready endpoints",
        "`400` rows",
        "Mean exact quality was `0.135`",
        "Mean exact quality was `0.135` for `qwen3_4b_vllm` and `0.040` for `qwen3_0_6b_vllm`",
        "Local Policy-Matrix Handoff",
        "local_policy_matrices_phase2_local_vllm_two_model_all200_nothink/local_query_model_utility.csv",
        "local_policy_matrices_phase2_local_vllm_two_model_all200_nothink/local_state_model_utility.csv",
        "true_probe_policy_inputs_phase2_local_vllm_two_model_all200_nothink/true_probe_query_model_utility.csv",
        "true_probe_policy_phase2_local_vllm_two_model_all200_nothink/table_proberoute_policy.csv",
        "mean utility `0.0732`",
        "mean oracle regret `0.0244`",
        "Oracle-Gap Gate",
        "relative gap to the per-query oracle `<= 0.0300`",
        "experiments/68_benchmark_label_policy_export.py",
        "routecode_embedding_predicted:k32:alpha0",
        "dataset_model_rule:exact_math_qwen_intern",
        "targeted_exact_math_benchmark_label_rule",
        "math500 -> Qwen3-8B",
        "aime -> Intern-S1-mini",
        "current working system that is within 3% of oracle",
        "relative gap `0.0000`",
        "regret rows `0/41`",
        "operational fallback and diagnostic artifact",
        "exact-math test relative gap is `0.0265`",
        "policy_slice_candidate_not_val_selected",
        "relative gap `0.0263`",
        "relative gap of `0.0789`",
        "not val-selected",
        "Cost And Provider Scope",
        "OpenAI GPT-family models",
        "Anthropic Claude-family models",
        "Google Gemini-family models",
        "no GPT/Claude/Gemini API calls were made",
        "target-model input/output token cost",
        "local GPU latency/cost proxy",
        "router-token-saving claim",
        "vLLM OpenAI-compatible endpoint",
        "`http://localhost:8001/v1`",
        "thinking disabled",
        "20-row vLLM exact smoke",
        "2/20 exact-correct",
        "20-row vLLM probe smoke",
        "confidence parsed on 16/20 rows",
        "200-row vLLM exact run",
        "26/200 exact-correct",
        "200-row vLLM probe run",
        "confidence parsed on 158/200 rows",
        "vLLM all200",
        "selected model changed on `2/41`",
        "mean realized utility again stayed `0.8537`",
        "VOI again refuses to probe",
        "answer-output probe",
        "query-plus-probe state accuracy `0.6585`",
        "still no utility gain",
        "Qwen/Qwen3-4B@1cfa9a7208912126459214e8b04321603b3df60c",
        "local Hugging Face Transformers backend",
        "4 true local smoke rows",
        "118 true local exact-manifest rows",
        "200 true local exact-manifest rows",
        "zero generation errors",
        "8/118",
        "14/200",
        "200 true local cheap-probe rows",
        "164 aligned rows",
        "41 held-out utility rows",
        "mean quality `1.0000`",
        "query_plus_probe_state_predictor",
        "`0.5128`",
        "query_only_state_predictor",
        "`0.5641`",
        "`0.6341`",
        "`0.6098`",
        "confidence intervals overlap",
        "true local-probe M5",
        "voi_probe",
        "fraction_probed `0.0000`",
        "never_probe",
        "`0.8537`",
        "always_probe",
        "`-0.0590`",
        "zero cost",
        "for every positive cost multiplier",
        "never_probe is best",
        "VOI refuses to probe",
        "`7` true-probe cost settings",
        "decision value",
        "selected model changed on `1/41` held-out utility rows",
        "mean realized utility stayed `0.8537` before and after the probe update",
        "nonzero predicted-gain rows: `0/41`",
        "state_prediction_accuracy_ci_low",
        "utility_ci_low",
        "mean_net_utility_ci_low",
        "observability_gap_closed_ci_high",
        "state_observability_gap_ci_low",
        "query_oracle_gap_ci_high",
        "Not supported yet",
        "active_minus_uniform_mean_utility_mean",
        "active_minus_random_mean_utility_mean",
        "active_minus_dataset_mean_utility_mean",
        "active_minus_embedding_mean_utility_mean",
        "six held-out models",
        "72 paired rows",
        "+0.0082",
        "-0.0172",
        "-0.0138",
        "-0.0080",
        "K sensitivity sweep",
        "54 paired rows",
        "-0.0189",
        "-0.0085",
        "-0.0294",
        "-0.0313",
        "probe-cost multipliers",
        "VOI minus the best threshold policy",
        "`8` settings",
        "negative versus random examples",
        "negative versus dataset-stratified examples",
        "negative versus embedding-cluster examples",
    ]
    for phrase in required:
        assert phrase in text
